<a href="https://colab.research.google.com/github/rocks2021/rockspython/blob/main/08_ndarray_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Array Slicing & Negative Slicing

In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[1:5]) # [start:end(exclusively):step]

[2 3 4 5]


In [2]:
a[4:] # from 4 to the end (including the end)

array([5, 6, 7])

In [3]:
a[:4] # from the beginning to index 4(exclusively)

array([1, 2, 3, 4])

In [4]:
a[-3:-1]

array([5, 6])

In [5]:
a[1:5:2]

array([2, 4])

In [6]:
a[::2]

array([1, 3, 5, 7])

In [7]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b[1,1:4]

array([7, 8, 9])

In [8]:
b[0:2,2]

array([3, 8])

In [9]:
b[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [10]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[2]

2

In [12]:
x = np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
x[3][1]

10

In [14]:
s = np.arange(9)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
s[3:6]

array([3, 4, 5])

In [16]:
s[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
s[4:] #including the end

array([4, 5, 6, 7, 8])

In [18]:
s[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
y = np.array([10,20,30,40,50,60,70,80,90])
y

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
y[3]

40

In [21]:
y[-6]

40

In [22]:
y[3:-2]

array([40, 50, 60, 70])

In [23]:
y[-3:-1]

array([70, 80])

In [24]:
y[2:6:3]

array([30, 60])

In [25]:
y[:7:2]

array([10, 30, 50, 70])

In [26]:
z = np.arange(16).reshape(4,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
z[0:2,1:3]

array([[1, 2],
       [5, 6]])